
ActionBarSaverDB = {
	["restoreRank"] = false,
	["macro"] = false,
	["sets"] = {
		["DEATHKNIGHT"] = {
		},
		["WARRIOR"] = {
			["wororr"] = {
				nil, -- [1]
				nil, -- [2]
				nil, -- [3]
				nil, -- [4]
				nil, -- [5]
				nil, -- [6]
				nil, -- [7]
				nil, -- [8]
				nil, -- [9]
				nil, -- [10]
				nil, -- [11]
				nil, -- [12]
				"item|5512||Healthstone", -- [13]
				nil, -- [14]
				"item|69195||Vrykul Male Mask", -- [15]
				"item|17202||Snowball", -- [16]
				"item|49704||Carved Ogre Idol", -- [17]
				"item|6657||Savory Deviate Delight", -- [18]
				"item|71601||Gauntlets of the Molten Giant", -- [19]
				"macro|20|||Interface\\Icons\\Ability_ShockWave|#showtooltip Hamstring/n/cast Battle Stance/n/cast Hamstring", -- [20]
				"macro|21||Trinket14|Interface\\Icons\\SPELL_HOLY_CHAMPIONSBOND|/use 14/n/use 13", -- [21]
				"item|71250||Cinch of the Flaming Ember", -- [22]
				"macro|23|||Interface\\Icons\\INV_MISC_QUESTIONMARK|/cancelaura Hand of Protection/n/cancelaura Blessing of Protection", -- [23]
				"item|68806||Kalytha's Haunted Locket", -- [24]
				"spell|78||Heroic Strike||", -- [25]
				"spell|12294||Mortal Strike||", -- [26]
				"spell|7384||Overpower|Battle Stance|", -- [27]
				"spell|86346||Colossus Smash|Battle, Berserker Stance|", -- [28]
				"spell|18499||Berserker Rage||", -- [29]
				"spell|6673||Battle Shout||", -- [30]
				"item|71601||Gauntlets of the Molten Giant", -- [31]
				nil, -- [32]
				nil, -- [33]
				nil, -- [34]
				nil, -- [35]
				nil, -- [36]
				"macro|37|||Interface\\Icons\\Ability_Gouge|#showtooltip Rend/n/startattack/n/cast Battle Stance/n/cast Rend", -- [37]
				"spell|469||Commanding Shout||", -- [38]
				"macro|39|||Interface\\Icons\\INV_Sword_48|#showtooltip Execute/n/startattack/n/cast Berserker Stance/n/cast Execute", -- [39]
				"macro|40|||Interface\\Icons\\Inv_Misc_SummerFest_BrazierGreen|#showtooltip Green Fire hawk/n/use [flyable,nomounted] Pureblood Fire Hawk/n/use [noflyable,nomounted] Black Nightsaber/n/dismount [mounted]", -- [40]
				"macro|41|||Interface\\Icons\\Ability_Warrior_ShatteringThrow|#showtooltip Shattering Throw/n/cast Battle Stance/n/cast Shattering Throw", -- [41]
				"spell|6673||Battle Shout||", -- [42]
				"spell|6552||Pummel||", -- [43]
				"macro|44|||Interface\\Icons\\Spell_Nature_Reincarnation|#showtooltip Taunt/n/cast Defensive Stance/n/cast Taunt", -- [44]
				"spell|57755||Heroic Throw||", -- [45]
				"companion|16055|||MOUNT|", -- [46]
				nil, -- [47]
				"spell|78||Heroic Strike||", -- [48]
				"macro|49|||Interface\\Icons\\Ability_Rogue_SliceDice|#showtooltip Sweeping Strikes/n/cast Sweeping Strikes/n/use Blood Fury", -- [49]
				"macro|50|||Interface\\Icons\\Ability_CriticalStrike|#showtooltip Recklessness/n/cancelaura Retaliation/n/cancelaura Counterattack/n/cast Recklessness/n/use Blood Fury", -- [50]
				"macro|51|||INTERFACE\\ICONS\\achievement_boss_kingymiron|#showtooltip Deadly Calm/n/cancelaura Inner Rage/n/cast Deadly Calm/n/use Blood Fury/n/cast Heroic Strike", -- [51]
				"spell|46924||Bladestorm||", -- [52]
				"spell|97462||Rallying Cry||", -- [53]
				"spell|6544||Heroic Leap||", -- [54]
				"spell|34428||Victory Rush||", -- [55]
				"macro|56|||Interface\\Icons\\Ability_Warrior_Charge|#showtooltip Charge/n/cast Battle Stance/n/equipset dps/n/cast Charge/n/startattack", -- [56]
				"spell|1680||Whirlwind|Berserker Stance|", -- [57]
				nil, -- [58]
				nil, -- [59]
				nil, -- [60]
				"spell|97462||Rallying Cry||", -- [61]
				"item|58146||Golemblood Potion", -- [62]
				"item|71250||Cinch of the Flaming Ember", -- [63]
				"spell|46924||Bladestorm||", -- [64]
				"spell|6544||Heroic Leap||", -- [65]
				"spell|100||Charge|Battle Stance|", -- [66]
				"spell|34428||Victory Rush||", -- [67]
				"macro|68|||Interface\\Icons\\Ability_Warrior_Charge|#showtooltip Charge/n/cast Battle Stance/n/equipset dps/n/cast Charge/n/startattack", -- [68]
				"spell|1680||Whirlwind|Berserker Stance|", -- [69]
				nil, -- [70]
				nil, -- [71]
				nil, -- [72]
				"spell|78||Heroic Strike||", -- [73]
				"spell|845||Cleave||", -- [74]
				"macro|75|||Interface\\Icons\\Ability_Warrior_SavageBlow|#showtooltip Mortal Strike/n/startattack/n/equipset dps/n/cast Berserker Stance/n/cast Mortal Strike/n/cancelaura Free your mind/n/cancelaura Hand of Protection/n/cancelaura Blessing of Protection", -- [75]
				"macro|76|||Interface\\Icons\\Ability_MeleeDamage|#showtooltip Overpower/n/startattack/n/cast Battle Stance/n/cast Overpower", -- [76]
				"macro|77|||Interface\\Icons\\Ability_Warrior_DecisiveStrike|#showtooltip Slam/n/startattack/n/cast Berserker Stance/n/cast Slam", -- [77]
				"spell|469||Commanding Shout||", -- [78]
				"macro|79||CNCLAURA|Interface\\Icons\\INV_MISC_QUESTIONMARK|/cancelaura Bladestorm/n/cancelaura Inner Rage", -- [79]
				"macro|80|||Interface\\Icons\\Spell_Nature_ThunderClap|#showtooltip Thunder Clap/n/startattack/n/cast Battle Stance/n/cast Thunder Clap", -- [80]
				"macro|81|||INTERFACE\\ICONS\\ability_warrior_colossussmash|#showtooltip Colossus Smash/n/cast Berserker Stance/n/cast Colossus Smash/n/startattack", -- [81]
				"spell|3018||Shoot||", -- [82]
				"spell|5246||Intimidating Shout||", -- [83]
				"spell|55694||Enraged Regeneration||", -- [84]
				nil, -- [85]
				nil, -- [86]
				"macro|87|||Interface\\Icons\\Ability_Warrior_SavageBlow|#showtooltip Mortal Strike/n/startattack/n/equipset dps/n/cast Berserker Stance/n/cast Mortal Strike/n/cancelaura Free your mind/n/cancelaura Hand of Protection/n/cancelaura Blessing of Protection", -- [87]
				nil, -- [88]
				nil, -- [89]
				"spell|55694||Enraged Regeneration||", -- [90]
				"macro|91|||Interface\\Icons\\Ability_Warrior_VictoryRush|#showtooltip Intervene/n/cast Defensive Stance/n/cast [@mouseover, help, exists] [help] Intervene", -- [91]
				"macro|92||Wall|Interface\\Icons\\Ability_Warrior_DefensiveStance|/cancelaura Recklessness/n/cancelaura Bladestorm/n/equipset wall/n/cast Defensive Stance/n/cast Shield Wall", -- [92]
				"item|58146||Golemblood Potion", -- [93]
				"item|71250||Cinch of the Flaming Ember", -- [94]
				"macro|95|||Interface\\Icons\\Spell_Nature_AncestralGuardian|#showtooltip Berserker Rage/n/cast Berserker Rage/n/cast Inner Rage", -- [95]
				"spell|1134||Inner Rage||", -- [96]
				"spell|78||Heroic Strike||", -- [97]
				"spell|845||Cleave||", -- [98]
				"macro|99|||Interface\\Icons\\Ability_Warrior_SavageBlow|#showtooltip Mortal Strike/n/startattack/n/equipset dps/n/cast Berserker Stance/n/cast Mortal Strike/n/cancelaura Free your mind/n/cancelaura Hand of Protection/n/cancelaura Blessing of Protection", -- [99]
				"macro|100|||Interface\\Icons\\Ability_MeleeDamage|#showtooltip Overpower/n/startattack/n/cast Battle Stance/n/cast Overpower", -- [100]
				"macro|101|||Interface\\Icons\\Ability_Warrior_DecisiveStrike|#showtooltip Slam/n/startattack/n/cast Berserker Stance/n/cast Slam", -- [101]
				"spell|469||Commanding Shout||", -- [102]
				"macro|103||CNCLAURA|Interface\\Icons\\INV_MISC_QUESTIONMARK|/cancelaura Bladestorm/n/cancelaura Inner Rage", -- [103]
				"macro|104|||Interface\\Icons\\Spell_Nature_ThunderClap|#showtooltip Thunder Clap/n/startattack/n/cast Battle Stance/n/cast Thunder Clap", -- [104]
				"macro|105|||INTERFACE\\ICONS\\ability_warrior_colossussmash|#showtooltip Colossus Smash/n/cast Berserker Stance/n/cast Colossus Smash/n/startattack", -- [105]
				"companion|32244|||MOUNT|", -- [106]
				[109] = "spell|6603||Auto Attack||",
			},
		},
		["PALADIN"] = {
			["ret"] = {
				"macro|1||CS|Interface\\Icons\\Spell_Holy_CrusaderStrike|#showtooltip/n/cancelaura Hand of Protection/n/cancelaura Divine Shield/n/startattack/n/cast Crusader Strike", -- [1]
				"macro|2||DS|Interface\\Icons\\Ability_Paladin_DivineStorm|#showtooltip/n/startattack/n/cast Divine Storm", -- [2]
				"spell|85256||Templar's Verdict||", -- [3]
				"spell|20271||Judgement||", -- [4]
				"macro|5||Exo|Interface\\Icons\\Spell_Holy_Excorcism_02|#showtooltip/n/cancelaura Divine Shield/n/startattack/n/cast Exorcism", -- [5]
				"spell|1044||Hand of Freedom||", -- [6]
				"companion|98204|||MOUNT|", -- [7]
				"spell|28730||Arcane Torrent|Racial|", -- [8]
				"spell|853||Hammer of Justice||", -- [9]
				"spell|84963||Inquisition||", -- [10]
				"spell|28730||Arcane Torrent|Racial|", -- [11]
				nil, -- [12]
				"spell|20217||Blessing of Kings||", -- [13]
				"spell|7328||Redemption||", -- [14]
				"macro|15|||Interface\\Icons\\INV_MISC_QUESTIONMARK|#showtooltip Invincible/n/use [flyable,nomounted] Pureblood Fire Hawk/n/use [nomounted,noflyable] Amani Battle Bear/n/dismount [mounted]", -- [15]
				"spell|96231||Rebuke||", -- [16]
				"spell|26573||Consecration||", -- [17]
				"item|71443||Uncrushable Belt of Fury", -- [18]
				"spell|19740||Blessing of Might||", -- [19]
				"spell|31801||Seal of Truth||", -- [20]
				"item|58146||Golemblood Potion", -- [21]
				"macro|22||HW|Interface\\Icons\\Spell_Holy_PurifyingPower|#showtooltip/n/startattack/n/cast Holy Wrath", -- [22]
				"macro|23||HOW|Interface\\Icons\\INV_Hammer_04|#showtooltip/n/startattack/n/cast Hammer of Wrath", -- [23]
				"macro|24|||Interface\\Icons\\inv_gauntlets_plate_raidpaladin_j_01|/use Immolation Gauntlets", -- [24]
				"spell|35395||Crusader Strike||", -- [25]
				"spell|20271||Judgement||", -- [26]
				"spell|879||Exorcism||", -- [27]
				"spell|84963||Inquisition||", -- [28]
				"item|71513||Immolation Gauntlets", -- [29]
				"spell|31884||Avenging Wrath||", -- [30]
				"macro|31||Zea|Interface\\Icons\\Spell_Holy_ProclaimChampion_02|#showtooltip Zealotry/n/cast Zealotry/n/startattack", -- [31]
				"spell|86150||Guardian of Ancient Kings||", -- [32]
				"spell|6940||Hand of Sacrifice||", -- [33]
				"spell|1022||Hand of Protection||", -- [34]
				"spell|6940||Hand of Sacrifice||", -- [35]
				"spell|633||Lay on Hands||", -- [36]
				"macro|37|||Interface\\Icons\\INV_MISC_QUESTIONMARK|/cancelaura Divine Shield", -- [37]
				"spell|19750||Flash of Light||", -- [38]
				"macro|39|||Interface\\Icons\\Spell_Holy_LayOnHands|#showtooltip Lay on Hands/n/cast [@mouseover,help,nodead] Lay on Hands", -- [39]
				"macro|40|||Interface\\Icons\\Spell_Holy_Purify|#showtooltip Cleanse/n/cast [@mouseover,help,nodead] Cleanse", -- [40]
				"spell|20154||Seal of Righteousness||", -- [41]
				"macro|42|||Interface\\Icons\\Spell_Holy_SealOfProtection|#showtooltip Hand of Protection/n/cast [@mouseover,help,nodead] Hand of Protection", -- [42]
				"spell|62124||Hand of Reckoning||", -- [43]
				"macro|44|||Interface\\Icons\\Spell_Holy_SealOfSacrifice|#showtooltip Hand of Sacrifice/n/cast [@mouseover,help,nodead] Hand of Sacrifice", -- [44]
				"macro|45|||Interface\\Icons\\Spell_Holy_SealOfSalvation|#showtooltip Hand of Salvation/n/cast [@mouseover,help,nodead] Hand of Salvation", -- [45]
				nil, -- [46]
				"spell|7328||Redemption||", -- [47]
				"spell|62124||Hand of Reckoning||", -- [48]
				nil, -- [49]
				nil, -- [50]
				nil, -- [51]
				nil, -- [52]
				"item|71443||Uncrushable Belt of Fury", -- [53]
				"spell|633||Lay on Hands||", -- [54]
				"spell|642||Divine Shield||", -- [55]
				"spell|1022||Hand of Protection||", -- [56]
				"spell|498||Divine Protection||", -- [57]
				nil, -- [58]
				"spell|20154||Seal of Righteousness||", -- [59]
				"spell|31801||Seal of Truth||", -- [60]
				"macro|61||W|Interface\\Icons\\SPELL_HOLY_AVENGINEWRATH|#showtooltip Avenging Wrath/n/cast Avenging Wrath/n/use Apparatus of Khaz'goroth/n/use Immolation Gauntlets/n/startattack", -- [61]
				"macro|62||Zea|Interface\\Icons\\Spell_Holy_ProclaimChampion_02|#showtooltip Zealotry/n/cast Zealotry/n/startattack", -- [62]
				"macro|63||Guar|Interface\\Icons\\Spell_Holy_Heroism|#showtooltip/n/cast Guardian of ancient kings", -- [63]
				"spell|498||Divine Protection||", -- [64]
				"spell|642||Divine Shield||", -- [65]
				"spell|54428||Divine Plea||", -- [66]
				"spell|84963||Inquisition||", -- [67]
				"spell|498||Divine Protection||", -- [68]
				"item|5512||Healthstone", -- [69]
				nil, -- [70]
				"spell|853||Hammer of Justice||", -- [71]
				"spell|19750||Flash of Light||", -- [72]
				[85] = "macro|85||DS|Interface\\Icons\\Ability_Paladin_DivineStorm|#showtooltip/n/startattack/n/cast Divine Storm",
				[86] = "macro|86||HOW|Interface\\Icons\\INV_Hammer_04|#showtooltip/n/startattack/n/cast Hammer of Wrath",
				[87] = "macro|87||Exo|Interface\\Icons\\Spell_Holy_Excorcism_02|#showtooltip/n/cancelaura Divine Shield/n/startattack/n/cast Exorcism",
			},
		},
		["MAGE"] = {
		},
		["PRIEST"] = {
		},
		["WARLOCK"] = {
		},
		["HUNTER"] = {
		},
		["DRUID"] = {
		},
		["SHAMAN"] = {
		},
		["ROGUE"] = {
		},
	},
	["spellSubs"] = {
	},
	["checkCount"] = false,
}
